runtime: nodejs16

instance_class: F2

env_variables:
  BUCKET_NAME: "ng-app-perfume"

handlers:
  - url: /
    static_files: dist/Shisha/index.html
    upload: dist/Shisha/index.html

  - url: /
    static_dir: dist/Shisha
